// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6rBrU5VcBntu4QQ6OYDvdJQptI55mZ0',
    appId: '1:777696090287:web:862a2302c2eae3d9359c5a',
    messagingSenderId: '777696090287',
    projectId: 'tubi-home',
    authDomain: 'tubi-home.firebaseapp.com',
    storageBucket: 'tubi-home.firebasestorage.app',
    measurementId: 'G-94KWFGB7WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR8ZHQO14T76_67k33xCkJ0ty0coctqnY',
    appId: '1:777696090287:android:d9c95a5b3afb7707359c5a',
    messagingSenderId: '777696090287',
    projectId: 'tubi-home',
    storageBucket: 'tubi-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzsyZvoTNEb3e59X4UnztiMXN62YCM3G8',
    appId: '1:777696090287:ios:ab3a671c517e38fa359c5a',
    messagingSenderId: '777696090287',
    projectId: 'tubi-home',
    storageBucket: 'tubi-home.firebasestorage.app',
    iosClientId: '777696090287-q7o7b4amq79msap9ed7jth8i0afbhm7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubiHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzsyZvoTNEb3e59X4UnztiMXN62YCM3G8',
    appId: '1:777696090287:ios:ab3a671c517e38fa359c5a',
    messagingSenderId: '777696090287',
    projectId: 'tubi-home',
    storageBucket: 'tubi-home.firebasestorage.app',
    iosClientId: '777696090287-q7o7b4amq79msap9ed7jth8i0afbhm7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubiHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh6rBrU5VcBntu4QQ6OYDvdJQptI55mZ0',
    appId: '1:777696090287:web:71dd82b4152ab974359c5a',
    messagingSenderId: '777696090287',
    projectId: 'tubi-home',
    authDomain: 'tubi-home.firebaseapp.com',
    storageBucket: 'tubi-home.firebasestorage.app',
    measurementId: 'G-F9ZN3P75MX',
  );
}
